modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="sixheadeddragon"
version="1.0.0"
displayName="Six Headed Dragon"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="OwenHutton, MCreator"

[[dependencies.sixheadeddragon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



